In [13]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [14]:
url= "https://stats.inpredictable.com/nba/topGame.php?sort=ei&season=2024&team=ALL&po=0&frdt=2024-10-22&todt=2024-10-22"

page= requests.get(url)

soup= BeautifulSoup(page.text, 'html')

In [16]:
#<div class="iptbl"><table><tbody><tr><th>Rank</th><th>Season</th><th>Date</th><th onmouseover="tooltip.show(dScr)" onmouseout="tooltip.hide()" colspan="2">Score</th><th onmouseover="tooltip.show(dEI)" onmouseout="tooltip.hide()">Excitement</th><th onmouseover="tooltip.show(dTI)" onmouseout="tooltip.hide()"><a href="https://www.inpredictable.com/2016/06/inspired-by-last-nights-game-7-new.html" target="_blank">Tension</a></th><th onmouseover="tooltip.show(dCB)" onmouseout="tooltip.hide()">Comeback</th><th onmouseover="tooltip.show(dMVP)" onmouseout="tooltip.hide()">MVP</th><th onmouseover="tooltip.show(dLVP)" onmouseout="tooltip.hide()">LVP</th></tr><tr><td>1</td><td>2024</td><td>2024-10-22</td><td><a href="/nba/wpBox.php?gid=0022400062" target="_blank">MIN 103, LAL 110</a></td><td><span class="spk"><canvas width="50" height="20" style="display: inline-block; width: 50px; height: 20px; vertical-align: top;"></canvas></span></td><td>5.4</td><td>65.9</td><td>1.2</td><td>A. Davis: +19.7%</td><td>M. Conley: -13.3%</td></tr><tr><td>2</td><td>2024</td><td>2024-10-22</td><td><a href="/nba/wpBox.php?gid=0022400061" target="_blank">NYK 109, BOS 132</a></td><td><span class="spk"><canvas width="50" height="20" style="display: inline-block; width: 50px; height: 20px; vertical-align: top;"></canvas></span></td><td>2.0</td><td>37.1</td><td>1.0</td><td>J. Tatum: +17.4%</td><td>M. Bridges: -6.7%</td></tr></tbody></table></div>

In [ ]:
##Getting columns

In [24]:
table= soup.find('table')
columns= soup.find_all('th')
columns

[<th>Rank</th>,
 <th>Season</th>,
 <th>Date</th>,
 <th colspan="2" onmouseout="tooltip.hide()" onmouseover="tooltip.show(dScr)">Score</th>,
 <th onmouseout="tooltip.hide()" onmouseover="tooltip.show(dEI)">Excitement</th>,
 <th onmouseout="tooltip.hide()" onmouseover="tooltip.show(dTI)"><a href="https://www.inpredictable.com/2016/06/inspired-by-last-nights-game-7-new.html" target="_blank">Tension</a></th>,
 <th onmouseout="tooltip.hide()" onmouseover="tooltip.show(dCB)">Comeback</th>,
 <th onmouseout="tooltip.hide()" onmouseover="tooltip.show(dMVP)">MVP</th>,
 <th onmouseout="tooltip.hide()" onmouseover="tooltip.show(dLVP)">LVP</th>]

In [18]:
columns_list= [column.text for column in columns]
columns_list

['Rank',
 'Season',
 'Date',
 'Score',
 'Excitement',
 'Tension',
 'Comeback',
 'MVP',
 'LVP']

In [45]:
df= pd.DataFrame(columns=columns_list)
df

Empty DataFrame
Columns: [Rank, Season, Date, Score, Excitement, Tension, Comeback, MVP, LVP]
Index: []

In [46]:
#getting rows

In [47]:
rows= table.find_all('tr')[1:]
rows

[<tr><td>1</td><td>2024</td><td>2024-10-22</td><td><a href="/nba/wpBox.php?gid=0022400062" target="_blank">MIN 103, LAL 110</a></td><td><span class="spk">0.5,0.49,0.54,0.54,0.5,0.54,0.56,0.6,0.61,0.6,0.61,0.6,0.56,0.48,0.47,0.49,0.58,0.71,0.76,0.84,0.86,0.87,0.84,0.83,0.78,0.84,0.84,0.91,0.89,0.89,0.88,0.86,0.9,0.81,0.88,0.9,0.89,0.81,0.81,0.67,0.83,0.84,0.86,0.91,0.97,0.98,0.96,1,1,1</span></td><td>5.4</td><td>65.9</td><td>1.2</td><td>A. Davis: +19.7%</td><td>M. Conley: -13.3%</td></tr>,
 <tr><td>2</td><td>2024</td><td>2024-10-22</td><td><a href="/nba/wpBox.php?gid=0022400061" target="_blank">NYK 109, BOS 132</a></td><td><span class="spk">0.5,0.51,0.49,0.52,0.5,0.53,0.6,0.65,0.63,0.65,0.7,0.74,0.83,0.83,0.82,0.8,0.84,0.91,0.92,0.89,0.92,0.93,0.94,0.93,0.95,0.94,0.97,0.97,0.98,0.99,0.99,0.99,0.99,0.99,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1</span></td><td>2.0</td><td>37.1</td><td>1.0</td><td>J. Tatum: +17.4%</td><td>M. Bridges: -6.7%</td></tr>]

In [48]:
rows_list=[]
for row in rows:
    curr= row.find_all('td')
    curr.pop(4)
    rows_list.append([data.text for data in curr])

rows_list

[['1',
  '2024',
  '2024-10-22',
  'MIN 103, LAL 110',
  '5.4',
  '65.9',
  '1.2',
  'A. Davis: +19.7%',
  'M. Conley: -13.3%'],
 ['2',
  '2024',
  '2024-10-22',
  'NYK 109, BOS 132',
  '2.0',
  '37.1',
  '1.0',
  'J. Tatum: +17.4%',
  'M. Bridges: -6.7%']]

In [49]:
for row in rows_list:
    df.loc[len(df)]= row

df

,Rank,Season,Date,Score,Excitement,Tension,Comeback,MVP,LVP
0,1,2024,2024-10-22,"MIN 103, LAL 110",5.4,65.9,1.2,A. Davis: +19.7%,M. Conley: -13.3%
1,2,2024,2024-10-22,"NYK 109, BOS 132",2.0,37.1,1.0,J. Tatum: +17.4%,M. Bridges: -6.7%